name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: packages upgrade
      run: flutter packages upgrade
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
