name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk